on:
  push:
    branches:
    - master
jobs:
  build:
    name: 'Deploy to GCP'
    runs-on: ubuntu-latest
    env:
      APPLICATION_NAME: trains-bot
      PROJECT_ID: trains-bot-42
    steps:
    - uses: actions/checkout@v1
    - name: 'docker: build image'
      run: docker build -t $APPLICATION_NAME .
    - name: 'docker: tag image'
      run: docker tag $APPLICATION_NAME gcr.io/$PROJECT_ID/$APPLICATION_NAME:$GITHUB_SHA
    - name: 'gloud: setup'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 270.0.0
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
    - name: 'gcloud: configure docker'
      run: gcloud auth configure-docker --quiet
    - name: 'gcloud: push image'
      run: docker push gcr.io/$PROJECT_ID/$APPLICATION_NAME
